#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$application = new Application();

$application->add(new \AGuardia\Command\ProcessLatestPostsCommand());
$application->add(new \AGuardia\Command\ProcessReportedPostsCommand());

$application->run();
